# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/NSCSCC/NSCSCC_2021/project_1/project_1.srcs/sources_1/ip/unsigned_multiplier/unsigned_multiplier.xci
# IP: The module: 'unsigned_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NSCSCC/NSCSCC_2021/project_1/project_1.srcs/sources_1/ip/unsigned_multiplier/unsigned_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_multiplier'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/NSCSCC/NSCSCC_2021/project_1/project_1.srcs/sources_1/ip/unsigned_multiplier/unsigned_multiplier.xci
# IP: The module: 'unsigned_multiplier' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/NSCSCC/NSCSCC_2021/project_1/project_1.srcs/sources_1/ip/unsigned_multiplier/unsigned_multiplier_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'unsigned_multiplier'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
